tasks:
  - init: |
      echo "Willkommen in Ihrer Voice Cloning Umgebung."
      echo "Das Coqui TTS Docker Image ist startklar."
      # Hier könnten weitere Initialisierungs-Skripte stehen
    command: |
      echo "Um den TTS-Server zu starten, führen Sie 'tts-server --model_name tts_models/multilingual/multi-dataset/xtts_v2' aus."

# Konfiguration, um das Docker-Image zu verwenden
image:
  file: .gitpod.Dockerfile

# Ports, die wir für die Web-Oberfläche freigeben wollen
ports:
  - port: 5002
    onOpen: open-preview
