# Optimiertes Dockerfile für die Entwicklung

# Verwenden Sie das offizielle Coqui TTS Image als Basis.
# Eine feste Version sorgt für reproduzierbare Builds.
FROM ghcr.io/coqui-ai/tts:v0.22.0

# Legen Sie das Arbeitsverzeichnis fest.
WORKDIR /app

# (Optional) Installieren Sie zuerst die Abhängigkeiten, um den Docker-Cache zu nutzen.
# Kopieren Sie nur die Anforderungsdatei.
COPY requirements.txt .

# Installieren Sie die Pakete. Dieser Schritt wird nur dann erneut ausgeführt,
# wenn sich die requirements.txt ändert.
RUN pip install --no-cache-dir -r requirements.txt

# Kopieren Sie nun den restlichen Anwendungscode.
# Änderungen am Code führen nicht zu einer Neuinstallation der Abhängigkeiten.
COPY . .

# Standardbefehl für die Entwicklung: eine interaktive Shell.
# So können Sie den Container betreten und Befehle ausführen.
CMD ["/bin/bash"]
