# Es wird empfohlen, eine spezifische Version zu verwenden, um reproduzierbare Builds zu gewährleisten.
# Die offiziellen Coqui TTS-Images befinden sich jetzt auf ghcr.io.
FROM ghcr.io/coqui-ai/tts:v0.22.0

# Arbeitsverzeichnis im Container festlegen
WORKDIR /app

# Optional: Zusätzliche Systemabhängigkeiten installieren.
# Fügen Sie hier Ihre Pakete hinzu und bereinigen Sie den apt-Cache, um die Image-Größe zu reduzieren.
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     some-package \
#     && rm -rf /var/lib/apt/lists/*

# Optional: Anwendungsdateien in den Container kopieren
# COPY . .

# Standardbefehl beim Start des Containers.
# Für die Entwicklung (z.B. in Gitpod) ist eine interaktive Shell nützlich.
# Für die Produktion würden Sie hier den Befehl zum Starten Ihrer Anwendung angeben.
CMD ["/bin/bash"]
